spring.application.name=FormulaRac

spring.datasource.url=jdbc:h2:mem:formularac;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.h2.console.enabled=true
